name: Robot Framework

on:
  push:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run Robot Framework Tests 
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests  
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}/TestsBook/TestCases.robot
            ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports