name: Robot Framework
 
on:
  push:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: /home/runner/work/RF_BookCart/RF_BookCart/robot_tests
            ROBOT_REPORTS_DIR: /home/runner/work/RF_BookCart/RF_BookCart/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: /home/runner/work/RF_BookCart/RF_BookCart/robot_tests/reports